### ISSUE TITLE
Feature request: Download files

### ISSUE THREAD

**Issue by fsimkovic** [biomadeira/pyPDBeREST#2]
Are you considering an API for downloading specific files?

**Comment by biomadeira** [comment]
@fsimkovic sorry for the delay in replying to you. Do you mean to download structure files (PDB, mmCIF, etc.)?

**Comment by fsimkovic** [comment]
:+1: Indeed. Have you thought about this?

**Comment by biomadeira** [comment]
Didn't think of that but can try adding it. Thanks for the suggestion! ;)

**Comment by biomadeira** [comment]
@fsimkovic have a look at this https://github.com/biomadeira/BioDownloader

Not sure it was what you had in mind but it has been fun to set this up 😊
